<?php

define(MYSQL_IP, "IP_HERE");
define(MYSQL_USER, "USERNAME_HERE");
define(MYSQL_PASS, "PASSWORD_HERE");
define(MYSQL_DB, "DB_NAME_HERE");
define(PAYPAL_CLIENT_SECRET, "YOUR PAYPAL CLIENT SECRET HERE");
define(CONTACT_EMAIL, "EMAIL@ADDRESSTOSEND.TO");
